# Generated by Django 3.1.1 on 2020-09-14 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
